// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/custom/custom.proto)

#include "custom/custom.grpc.pb.h"
#include "plugins/custom/custom.h"

#include "mavsdk.h"

#include "lazy_plugin.h"

#include "log.h"
#include <atomic>
#include <cmath>
#include <future>
#include <limits>
#include <memory>
#include <mutex>
#include <sstream>
#include <vector>

namespace mavsdk {
namespace mavsdk_server {


template<typename Custom = Custom, typename LazyPlugin = LazyPlugin<Custom>>

class CustomServiceImpl final : public rpc::custom::CustomService::Service {
public:

    CustomServiceImpl(LazyPlugin& lazy_plugin) : _lazy_plugin(lazy_plugin) {}






    static std::unique_ptr<rpc::custom::Heartbeat> translateToRpcHeartbeat(const mavsdk::Custom::Heartbeat &heartbeat)
    {
        auto rpc_obj = std::make_unique<rpc::custom::Heartbeat>();


            
        rpc_obj->set_type(heartbeat.type);
            
        
            
        rpc_obj->set_autopilot(heartbeat.autopilot);
            
        
            
        rpc_obj->set_base_mode(heartbeat.base_mode);
            
        
            
        rpc_obj->set_custom_mode(heartbeat.custom_mode);
            
        
            
        rpc_obj->set_system_status(heartbeat.system_status);
            
        

        return rpc_obj;
    }

    static mavsdk::Custom::Heartbeat translateFromRpcHeartbeat(const rpc::custom::Heartbeat& heartbeat)
    {
        mavsdk::Custom::Heartbeat obj;


            
        obj.type = heartbeat.type();
            
        
            
        obj.autopilot = heartbeat.autopilot();
            
        
            
        obj.base_mode = heartbeat.base_mode();
            
        
            
        obj.custom_mode = heartbeat.custom_mode();
            
        
            
        obj.system_status = heartbeat.system_status();
            
        
        return obj;
    }



    grpc::Status SubscribeHeartbeat(grpc::ServerContext* /* context */, const mavsdk::rpc::custom::SubscribeHeartbeatRequest* /* request */, grpc::ServerWriter<rpc::custom::HeartbeatResponse>* writer) override
    {
        if (_lazy_plugin.maybe_plugin() == nullptr) {
            
            return grpc::Status::OK;
        }

        auto stream_closed_promise = std::make_shared<std::promise<void>>();
        auto stream_closed_future = stream_closed_promise->get_future();
        register_stream_stop_promise(stream_closed_promise);

        auto is_finished = std::make_shared<bool>(false);
        auto subscribe_mutex = std::make_shared<std::mutex>();

        const mavsdk::Custom::HeartbeatHandle handle = _lazy_plugin.maybe_plugin()->subscribe_heartbeat(
            [this, &writer, &stream_closed_promise, is_finished, subscribe_mutex, &handle](const mavsdk::Custom::Heartbeat heartbeat) {

            rpc::custom::HeartbeatResponse rpc_response;
        
            rpc_response.set_allocated_heartbeat(translateToRpcHeartbeat(heartbeat).release());
        

        

            std::unique_lock<std::mutex> lock(*subscribe_mutex);
            if (!*is_finished && !writer->Write(rpc_response)) {
                
                _lazy_plugin.maybe_plugin()->unsubscribe_heartbeat(handle);
                
                *is_finished = true;
                unregister_stream_stop_promise(stream_closed_promise);
                stream_closed_promise->set_value();
            }
        });

        stream_closed_future.wait();
        std::unique_lock<std::mutex> lock(*subscribe_mutex);
        *is_finished = true;

        return grpc::Status::OK;
    }


    void stop() {
        _stopped.store(true);
        std::lock_guard<std::mutex> lock(_stream_stop_mutex);
        for (auto& prom : _stream_stop_promises) {
            if (auto handle = prom.lock()) {
                handle->set_value();
            }
        }
    }

private:
    void register_stream_stop_promise(std::weak_ptr<std::promise<void>> prom) {
        // If we have already stopped, set promise immediately and don't add it to list.
        if (_stopped.load()) {
            if (auto handle = prom.lock()) {
                handle->set_value();
            }
        } else {
            std::lock_guard<std::mutex> lock(_stream_stop_mutex);
            _stream_stop_promises.push_back(prom);
        }
    }

    void unregister_stream_stop_promise(std::shared_ptr<std::promise<void>> prom) {
        std::lock_guard<std::mutex> lock(_stream_stop_mutex);
        for (auto it = _stream_stop_promises.begin(); it != _stream_stop_promises.end(); /* ++it */) {
            if (it->lock() == prom) {
                it = _stream_stop_promises.erase(it);
            } else {
                ++it;
            }
        }
    }


    LazyPlugin& _lazy_plugin;

    std::atomic<bool> _stopped{false};
    std::mutex _stream_stop_mutex{};
    std::vector<std::weak_ptr<std::promise<void>>> _stream_stop_promises {};
};

} // namespace mavsdk_server
} // namespace mavsdk