// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/striker/striker.proto)

#include <iomanip>

#include "striker_impl.h"
#include "plugins/striker/striker.h"

namespace mavsdk {

using Heartbeat = Striker::Heartbeat;
using SysStatus = Striker::SysStatus;
using RcChannel = Striker::RcChannel;
using Magnitometer = Striker::Magnitometer;

Striker::Striker(System& system) : PluginBase(), _impl{std::make_unique<StrikerImpl>(system)} {}

Striker::Striker(std::shared_ptr<System> system) :
    PluginBase(),
    _impl{std::make_unique<StrikerImpl>(system)}
{}

Striker::~Striker() {}

Striker::HeartbeatHandle Striker::subscribe_heartbeat(const HeartbeatCallback& callback)
{
    return _impl->subscribe_heartbeat(callback);
}

void Striker::unsubscribe_heartbeat(HeartbeatHandle handle)
{
    _impl->unsubscribe_heartbeat(handle);
}

Striker::Heartbeat Striker::heartbeat() const
{
    return _impl->heartbeat();
}

Striker::SysStatusHandle Striker::subscribe_sys_status(const SysStatusCallback& callback)
{
    return _impl->subscribe_sys_status(callback);
}

void Striker::unsubscribe_sys_status(SysStatusHandle handle)
{
    _impl->unsubscribe_sys_status(handle);
}

Striker::SysStatus Striker::sys_status() const
{
    return _impl->sys_status();
}

Striker::RcChannelHandle Striker::subscribe_rc_channel(const RcChannelCallback& callback)
{
    return _impl->subscribe_rc_channel(callback);
}

void Striker::unsubscribe_rc_channel(RcChannelHandle handle)
{
    _impl->unsubscribe_rc_channel(handle);
}

Striker::RcChannel Striker::rc_channel() const
{
    return _impl->rc_channel();
}

Striker::MagnitometerHandle Striker::subscribe_magnitometer(const MagnitometerCallback& callback)
{
    return _impl->subscribe_magnitometer(callback);
}

void Striker::unsubscribe_magnitometer(MagnitometerHandle handle)
{
    _impl->unsubscribe_magnitometer(handle);
}

Striker::Magnitometer Striker::magnitometer() const
{
    return _impl->magnitometer();
}

bool operator==(const Striker::Heartbeat& lhs, const Striker::Heartbeat& rhs)
{
    return (rhs.custom_mode == lhs.custom_mode) && (rhs.type == lhs.type) &&
           (rhs.autopilot == lhs.autopilot) && (rhs.base_mode == lhs.base_mode) &&
           (rhs.system_status == lhs.system_status) && (rhs.mavlink_version == lhs.mavlink_version);
}

std::ostream& operator<<(std::ostream& str, Striker::Heartbeat const& heartbeat)
{
    str << std::setprecision(15);
    str << "heartbeat:" << '\n' << "{\n";
    str << "    custom_mode: " << heartbeat.custom_mode << '\n';
    str << "    type: " << heartbeat.type << '\n';
    str << "    autopilot: " << heartbeat.autopilot << '\n';
    str << "    base_mode: " << heartbeat.base_mode << '\n';
    str << "    system_status: " << heartbeat.system_status << '\n';
    str << "    mavlink_version: " << heartbeat.mavlink_version << '\n';
    str << '}';
    return str;
}

bool operator==(const Striker::SysStatus& lhs, const Striker::SysStatus& rhs)
{
    return (rhs.onboard_control_sensors_present == lhs.onboard_control_sensors_present) &&
           (rhs.onboard_control_sensors_enabled == lhs.onboard_control_sensors_enabled) &&
           (rhs.onboard_control_sensors_health == lhs.onboard_control_sensors_health) &&
           (rhs.load == lhs.load) && (rhs.voltage_battery == lhs.voltage_battery) &&
           (rhs.current_battery == lhs.current_battery) &&
           (rhs.drop_rate_comm == lhs.drop_rate_comm) && (rhs.errors_comm == lhs.errors_comm) &&
           (rhs.errors_count1 == lhs.errors_count1) && (rhs.errors_count2 == lhs.errors_count2) &&
           (rhs.errors_count3 == lhs.errors_count3) && (rhs.errors_count4 == lhs.errors_count4) &&
           (rhs.battery_remaining == lhs.battery_remaining) &&
           (rhs.onboard_control_sensors_present_extended ==
            lhs.onboard_control_sensors_present_extended) &&
           (rhs.onboard_control_sensors_enabled_extended ==
            lhs.onboard_control_sensors_enabled_extended) &&
           (rhs.onboard_control_sensors_health_extended ==
            lhs.onboard_control_sensors_health_extended);
}

std::ostream& operator<<(std::ostream& str, Striker::SysStatus const& sys_status)
{
    str << std::setprecision(15);
    str << "sys_status:" << '\n' << "{\n";
    str << "    onboard_control_sensors_present: " << sys_status.onboard_control_sensors_present
        << '\n';
    str << "    onboard_control_sensors_enabled: " << sys_status.onboard_control_sensors_enabled
        << '\n';
    str << "    onboard_control_sensors_health: " << sys_status.onboard_control_sensors_health
        << '\n';
    str << "    load: " << sys_status.load << '\n';
    str << "    voltage_battery: " << sys_status.voltage_battery << '\n';
    str << "    current_battery: " << sys_status.current_battery << '\n';
    str << "    drop_rate_comm: " << sys_status.drop_rate_comm << '\n';
    str << "    errors_comm: " << sys_status.errors_comm << '\n';
    str << "    errors_count1: " << sys_status.errors_count1 << '\n';
    str << "    errors_count2: " << sys_status.errors_count2 << '\n';
    str << "    errors_count3: " << sys_status.errors_count3 << '\n';
    str << "    errors_count4: " << sys_status.errors_count4 << '\n';
    str << "    battery_remaining: " << sys_status.battery_remaining << '\n';
    str << "    onboard_control_sensors_present_extended: "
        << sys_status.onboard_control_sensors_present_extended << '\n';
    str << "    onboard_control_sensors_enabled_extended: "
        << sys_status.onboard_control_sensors_enabled_extended << '\n';
    str << "    onboard_control_sensors_health_extended: "
        << sys_status.onboard_control_sensors_health_extended << '\n';
    str << '}';
    return str;
}

bool operator==(const Striker::RcChannel& lhs, const Striker::RcChannel& rhs)
{
    return (rhs.time_boot_ms == lhs.time_boot_ms) && (rhs.chan1_raw == lhs.chan1_raw) &&
           (rhs.chan2_raw == lhs.chan2_raw) && (rhs.chan3_raw == lhs.chan3_raw) &&
           (rhs.chan4_raw == lhs.chan4_raw) && (rhs.chan5_raw == lhs.chan5_raw) &&
           (rhs.chan6_raw == lhs.chan6_raw) && (rhs.chan7_raw == lhs.chan7_raw) &&
           (rhs.chan8_raw == lhs.chan8_raw) && (rhs.chan9_raw == lhs.chan9_raw) &&
           (rhs.chan10_raw == lhs.chan10_raw) && (rhs.chan11_raw == lhs.chan11_raw) &&
           (rhs.chan12_raw == lhs.chan12_raw) && (rhs.chan13_raw == lhs.chan13_raw) &&
           (rhs.chan14_raw == lhs.chan14_raw) && (rhs.chan15_raw == lhs.chan15_raw) &&
           (rhs.chan16_raw == lhs.chan16_raw) && (rhs.chan17_raw == lhs.chan17_raw) &&
           (rhs.chan18_raw == lhs.chan18_raw) && (rhs.chancount == lhs.chancount) &&
           (rhs.rssi == lhs.rssi);
}

std::ostream& operator<<(std::ostream& str, Striker::RcChannel const& rc_channel)
{
    str << std::setprecision(15);
    str << "rc_channel:" << '\n' << "{\n";
    str << "    time_boot_ms: " << rc_channel.time_boot_ms << '\n';
    str << "    chan1_raw: " << rc_channel.chan1_raw << '\n';
    str << "    chan2_raw: " << rc_channel.chan2_raw << '\n';
    str << "    chan3_raw: " << rc_channel.chan3_raw << '\n';
    str << "    chan4_raw: " << rc_channel.chan4_raw << '\n';
    str << "    chan5_raw: " << rc_channel.chan5_raw << '\n';
    str << "    chan6_raw: " << rc_channel.chan6_raw << '\n';
    str << "    chan7_raw: " << rc_channel.chan7_raw << '\n';
    str << "    chan8_raw: " << rc_channel.chan8_raw << '\n';
    str << "    chan9_raw: " << rc_channel.chan9_raw << '\n';
    str << "    chan10_raw: " << rc_channel.chan10_raw << '\n';
    str << "    chan11_raw: " << rc_channel.chan11_raw << '\n';
    str << "    chan12_raw: " << rc_channel.chan12_raw << '\n';
    str << "    chan13_raw: " << rc_channel.chan13_raw << '\n';
    str << "    chan14_raw: " << rc_channel.chan14_raw << '\n';
    str << "    chan15_raw: " << rc_channel.chan15_raw << '\n';
    str << "    chan16_raw: " << rc_channel.chan16_raw << '\n';
    str << "    chan17_raw: " << rc_channel.chan17_raw << '\n';
    str << "    chan18_raw: " << rc_channel.chan18_raw << '\n';
    str << "    chancount: " << rc_channel.chancount << '\n';
    str << "    rssi: " << rc_channel.rssi << '\n';
    str << '}';
    return str;
}

bool operator==(const Striker::Magnitometer& lhs, const Striker::Magnitometer& rhs)
{
    return ((std::isnan(rhs.x) && std::isnan(lhs.x)) || rhs.x == lhs.x) &&
           ((std::isnan(rhs.y) && std::isnan(lhs.y)) || rhs.y == lhs.y) &&
           ((std::isnan(rhs.z) && std::isnan(lhs.z)) || rhs.z == lhs.z) &&
           ((std::isnan(rhs.magnetic_heading) && std::isnan(lhs.magnetic_heading)) ||
            rhs.magnetic_heading == lhs.magnetic_heading);
}

std::ostream& operator<<(std::ostream& str, Striker::Magnitometer const& magnitometer)
{
    str << std::setprecision(15);
    str << "magnitometer:" << '\n' << "{\n";
    str << "    x: " << magnitometer.x << '\n';
    str << "    y: " << magnitometer.y << '\n';
    str << "    z: " << magnitometer.z << '\n';
    str << "    magnetic_heading: " << magnitometer.magnetic_heading << '\n';
    str << '}';
    return str;
}

} // namespace mavsdk