// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/custom/custom.proto)

#pragma once

#include <array>
#include <cmath>
#include <functional>
#include <limits>
#include <memory>
#include <string>
#include <utility>
#include <vector>


#include "plugin_base.h"

#include "handle.h"

namespace mavsdk {


class System;class CustomImpl;

/**
 * @brief Definition of the CustomPlugin service
 */
class Custom : public PluginBase {
public:

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto custom = Custom(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit Custom(System& system); // deprecated

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto custom = Custom(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit Custom(std::shared_ptr<System> system); // new


    /**
     * @brief Destructor (internal use only).
     */
    ~Custom() override;





    /**
     * @brief Definition of Heartbeat Message
     */
    struct Heartbeat {
        
        uint32_t type{}; /**< @brief Device type (GCS, Autopilot, etc.) */
        uint32_t autopilot{}; /**< @brief Autopilot type */
        uint32_t base_mode{}; /**< @brief Basic mode */
        uint32_t custom_mode{}; /**< @brief Custom mode */
        uint32_t system_status{}; /**< @brief System status */
    };

    /**
     * @brief Equal operator to compare two `Custom::Heartbeat` objects.
     *
     * @return `true` if items are equal.
     */
    friend bool operator==(const Custom::Heartbeat& lhs, const Custom::Heartbeat& rhs);

    /**
     * @brief Stream operator to print information about a `Custom::Heartbeat`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, Custom::Heartbeat const& heartbeat);




    /**
     * @brief Connection state type.
     */
    struct ConnectionStatus {
        
        bool is_connected{}; /**< @brief Whether the vehicle got connected or disconnected */
    };

    /**
     * @brief Equal operator to compare two `Custom::ConnectionStatus` objects.
     *
     * @return `true` if items are equal.
     */
    friend bool operator==(const Custom::ConnectionStatus& lhs, const Custom::ConnectionStatus& rhs);

    /**
     * @brief Stream operator to print information about a `Custom::ConnectionStatus`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, Custom::ConnectionStatus const& connection_status);





        

    /**
     * @brief Callback type for subscribe_heartbeat.
     */
    using HeartbeatCallback = std::function<void(Heartbeat)>;

    /**
     * @brief Handle type for subscribe_heartbeat.
     */
    using HeartbeatHandle = Handle<Heartbeat>;

    /**
     * @brief Subscribe to Heartbeat
     */
    HeartbeatHandle subscribe_heartbeat(const HeartbeatCallback& callback);

    /**
     * @brief Unsubscribe from subscribe_heartbeat
     */
    void unsubscribe_heartbeat(HeartbeatHandle handle);

        



    /**
     * @brief Poll for 'Heartbeat' (blocking).
     *
     * @return One Heartbeat update.
     */
    Heartbeat heartbeat() const;




        

    /**
     * @brief Callback type for subscribe_connection_status.
     */
    using ConnectionStatusCallback = std::function<void(ConnectionStatus)>;

    /**
     * @brief Handle type for subscribe_connection_status.
     */
    using ConnectionStatusHandle = Handle<ConnectionStatus>;

    /**
     * @brief Subscribe to Connection Status
     */
    ConnectionStatusHandle subscribe_connection_status(const ConnectionStatusCallback& callback);

    /**
     * @brief Unsubscribe from subscribe_connection_status
     */
    void unsubscribe_connection_status(ConnectionStatusHandle handle);

        



    /**
     * @brief Poll for 'ConnectionStatus' (blocking).
     *
     * @return One ConnectionStatus update.
     */
    ConnectionStatus connection_status() const;




    /**
     * @brief Copy constructor.
     */
    Custom(const Custom& other);

    /**
     * @brief Equality operator (object is not copyable).
     */
    const Custom& operator=(const Custom&) = delete;

private:
    /** @private Underlying implementation, set at instantiation */
    std::unique_ptr<CustomImpl> _impl;
};

} // namespace mavsdk