// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/custom/custom.proto)

#include <iomanip>

#include "custom_impl.h"
#include "plugins/custom/custom.h"

namespace mavsdk {

using Heartbeat = Custom::Heartbeat;



Custom::Custom(System& system) : PluginBase(), _impl{std::make_unique<CustomImpl>(system)} {}

Custom::Custom(std::shared_ptr<System> system) : PluginBase(), _impl{std::make_unique<CustomImpl>(system)} {}


Custom::~Custom() {}

    
Custom::HeartbeatHandle Custom::subscribe_heartbeat(const HeartbeatCallback& callback)
{
    return _impl->subscribe_heartbeat(callback);
}

void Custom::unsubscribe_heartbeat(HeartbeatHandle handle)
{
    _impl->unsubscribe_heartbeat(handle);
}
    




Custom::Heartbeat
Custom::heartbeat() const
{
    return _impl->heartbeat();
}



bool operator==(const Custom::Heartbeat& lhs, const Custom::Heartbeat& rhs)
{
    return
        (rhs.type == lhs.type) &&
        (rhs.autopilot == lhs.autopilot) &&
        (rhs.base_mode == lhs.base_mode) &&
        (rhs.custom_mode == lhs.custom_mode) &&
        (rhs.system_status == lhs.system_status);
}

std::ostream& operator<<(std::ostream& str, Custom::Heartbeat const& heartbeat)
{
    str << std::setprecision(15);
    str << "heartbeat:" << '\n'
        << "{\n";
    str << "    type: " << heartbeat.type << '\n';
    str << "    autopilot: " << heartbeat.autopilot << '\n';
    str << "    base_mode: " << heartbeat.base_mode << '\n';
    str << "    custom_mode: " << heartbeat.custom_mode << '\n';
    str << "    system_status: " << heartbeat.system_status << '\n';
    str << '}';
    return str;
}




} // namespace mavsdk